#!/usr/bin/env bash
# config.sh — writes config/node.yaml and .env

step_config() {
    set -euo pipefail
    local sentinel="${HOME}/.myconex/.installed_config"
    local node_yaml="${MYCONEX_REPO_ROOT:?}/config/node.yaml"
    local env_file="${MYCONEX_REPO_ROOT}/.env"

    # node.yaml: never overwrite on upgrade (merge semantics)
    if [[ ! -f "$node_yaml" ]] || [[ -n "${REINSTALL:-}" ]]; then
        log_step "Writing config/node.yaml"
        cat > "$node_yaml" <<YAML
# MYCONEX Node Config — generated by installer
# Override any setting here; takes priority over mesh_config.yaml defaults.

node:
  name: "${MYCONEX_NODE_NAME:-}"
  tier: "${MYCONEX_DETECTED_TIER:-}"
  roles: []
  description: ""

mesh:
  static_peers: []
YAML
    else
        log_step "config/node.yaml exists — skipping (use --reinstall to overwrite)"
    fi

    # .env: create from example if absent, never overwrite values
    if [[ ! -f "$env_file" ]]; then
        log_step "Writing .env"
        cp "${MYCONEX_REPO_ROOT}/.env.example" "$env_file" 2>/dev/null || touch "$env_file"
    fi

    # Write collected secrets as real values (idempotent — sed replaces existing keys)
    for key_val in \
        "DISCORD_BOT_TOKEN:${DISCORD_BOT_TOKEN:-}" \
        "OPENROUTER_API_KEY:${OPENROUTER_API_KEY:-}" \
        "NOUS_API_KEY:${NOUS_API_KEY:-}" \
        "GMAIL_CLIENT_ID:${GMAIL_CLIENT_ID:-}" \
        "GMAIL_CLIENT_SECRET:${GMAIL_CLIENT_SECRET:-}"; do
        local key="${key_val%%:*}"
        local val="${key_val#*:}"
        [[ -z "$val" ]] && continue
        if grep -q "^${key}=" "$env_file"; then
            sed -i "s|^${key}=.*|${key}=${val}|" "$env_file"
        else
            echo "${key}=${val}" >> "$env_file"
        fi
    done

    mkdir -p "$(dirname "$sentinel")"; touch "$sentinel"
    log_step "config: done"
}
