"""
MYCONEX RLMAgent — Recursive Language Model Agent
==================================================
Phase 4: Ties together delegation, REPL tools, context management, and
persistent memory into a self-improving, autonomously reasoning agent.

RLMAgent extends HermesMoEAgent and adds:

  1. Complexity-driven task decomposition
     Score task complexity → if above threshold, decompose into sub-tasks and
     delegate them in parallel (agent-as-employee pattern).

  2. Persistent Python REPL
     Agents can execute Python to inspect/transform data without loading
     it into context (avoids context rot).

  3. Hierarchical context management
     RLMContextManager tracks token budgets across the delegation tree.
     Low-priority turns are pruned automatically.

  4. Session + cross-session memory (subconscious layer)
     SessionMemory watches interaction patterns within a session.
     PersistentMemoryStore persists facts, preferences, and summaries
     across sessions.

  5. Self-optimization loop (MiroThinker-inspired)
     After every N tasks, the agent analyses its own performance metrics
     and updates strategy notes stored in persistent memory.

  6. Natural language tool dispatch (VESPER-inspired)
     parse_tool_call() maps plain-English instructions to registered tools.

  7. Discord gateway integration hook
     on_discord_message() / format_discord_response() bridge the agent
     to discord_gateway.py.

  8. MoE sub-agent selection
     Builds on the existing HermesMoE complexity scorer to select the
     appropriate expert for each sub-task delegation.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Coroutine, Optional

from orchestration.agents.base_agent import (
    AgentConfig,
    AgentContext,
    AgentResult,
    AgentRole,
    Turn,
    _estimate_complexity,
)
from orchestration.agents.context_manager import (
    ContextFrame,
    PersistentMemoryStore,
    Priority,
    RLMContextManager,
    SessionMemory,
    estimate_messages_tokens,
    get_persistent_store,
)
from core.gateway.python_repl import REPL_POOL, REPLResult, WebPageReader

# HermesMoEAgent is imported conditionally to allow fallback
try:
    from integrations.moe_hermes_integration import (
        HermesMoEAgent,
        _score_complexity,
        create_moe_hermes_agent,
    )
    _MOE_AVAILABLE = True
except ImportError:
    from orchestration.agents.base_agent import InferenceAgent as HermesMoEAgent  # type: ignore[assignment]
    _score_complexity = _estimate_complexity  # type: ignore[assignment]
    _MOE_AVAILABLE = False

logger = logging.getLogger(__name__)


# ─── Task Decomposition Result ────────────────────────────────────────────────

@dataclass
class SubTask:
    """A single unit of work generated by task decomposition."""
    task_type: str
    payload: dict
    description: str = ""
    priority: int = Priority.HIGH


@dataclass
class DecompositionPlan:
    """The result of decomposing a complex task into sub-tasks."""
    strategy: str                             # "parallel" | "sequential" | "single"
    sub_tasks: list[SubTask] = field(default_factory=list)
    rationale: str = ""


# ─── Tool Registry ────────────────────────────────────────────────────────────

@dataclass
class ToolEntry:
    """Registered agent-callable tool."""
    name: str
    description: str
    handler: Callable[..., Coroutine]
    keywords: list[str] = field(default_factory=list)


# ─── Performance Metrics ──────────────────────────────────────────────────────

@dataclass
class TaskMetrics:
    task_id: str
    task_type: str
    complexity: float
    success: bool
    duration_ms: float
    tokens_used: int
    model_used: str
    delegation_depth: int
    sub_tasks_spawned: int


# ─── RLM Agent ────────────────────────────────────────────────────────────────

class RLMAgent(HermesMoEAgent):
    """
    Recursive Language Model Agent.

    The main reasoning engine for MYCONEX.  Orchestrates delegation, REPL-based
    data transformation, context management, memory, and self-optimization.

    Usage:
        from orchestration.agents.rlm_agent import create_rlm_agent
        agent = create_rlm_agent(name="rlm-primary")
        await agent.start()
        result = await agent.dispatch("task-001", "chat", {"prompt": "Analyse..."})
    """

    # Complexity threshold above which the agent tries to decompose the task
    DECOMPOSE_THRESHOLD: float = 0.60
    # Number of tasks between self-optimization runs
    OPTIMIZE_EVERY_N: int = 20
    # Maximum sub-tasks from a single decomposition
    MAX_SUB_TASKS: int = 6
    # Token fraction to reserve for memory context injection
    MEMORY_CONTEXT_FRACTION: float = 0.15

    def __init__(
        self,
        config: AgentConfig,
        moe_router=None,
        context_budget: int = 16384,
        max_delegation_depth: int = 4,
        memory_namespace: str = "global",
        enable_self_optimization: bool = True,
        enable_memory: bool = True,
    ) -> None:
        super().__init__(config, moe_router)

        self.context_manager = RLMContextManager(
            total_budget=context_budget,
            max_depth=max_delegation_depth,
        )
        self.session_memory = SessionMemory(session_id=config.name)
        self.persistent_memory: Optional[PersistentMemoryStore] = (
            get_persistent_store(memory_namespace) if enable_memory else None
        )
        self.enable_self_optimization = enable_self_optimization
        self.enable_memory = enable_memory

        self._tools: dict[str, ToolEntry] = {}
        self._metrics_log: list[TaskMetrics] = []
        self._tasks_since_optimize: int = 0
        self._web_reader = WebPageReader()

        self._register_default_tools()

    # ─── Lifecycle ────────────────────────────────────────────────────────────

    async def on_start(self) -> None:
        """Bootstrap memory and tool index on agent start."""
        if self.enable_memory and self.persistent_memory:
            self.persistent_memory.load()
        logger.info(
            "[rlm:%s] started. tools=%d memory=%s moe=%s",
            self.name, len(self._tools),
            "on" if self.enable_memory else "off",
            "on" if _MOE_AVAILABLE else "off",
        )

    async def on_stop(self) -> None:
        """Persist memory and flush REPL sessions on stop."""
        if self.enable_memory and self.persistent_memory:
            self.persistent_memory.save()
        await REPL_POOL.reset_session(self.name)
        logger.info("[rlm:%s] stopped. tasks=%d", self.name, self._total_tasks)

    # ─── Core: handle_task ────────────────────────────────────────────────────

    async def handle_task(
        self,
        task_id: str,
        task_type: str,
        payload: dict,
        context: Optional[AgentContext] = None,
    ) -> AgentResult:
        """
        Main task entry point.

        Decision flow:
          1. Score complexity
          2. If complex AND router available → decompose + delegate
          3. Else → direct LLM inference via MoE chain
          4. Inject memory context before LLM call
          5. Record metrics, trigger self-optimization every N tasks
        """
        start = time.time()

        if context is None:
            context = AgentContext()

        # Build messages for complexity scoring
        messages = context.to_messages()
        prompt = payload.get("prompt") or payload.get("message") or payload.get("query", "")
        if prompt:
            messages.append({"role": "user", "content": prompt})

        complexity = _score_complexity(messages) if messages else 0.5

        # Push a context frame for budget tracking
        root_frame = self.context_manager.push_frame(
            agent_name=self.name,
            task_type=task_type,
            task_id=task_id,
        )

        result: AgentResult
        sub_tasks_spawned = 0

        try:
            delegation_info = payload.get("_delegation", {})
            current_depth = delegation_info.get("depth", 0)

            # ── Decompose complex tasks ────────────────────────────────────
            if (
                complexity >= self.DECOMPOSE_THRESHOLD
                and self._router is not None
                and current_depth < self.MAX_DELEGATION_DEPTH
                and task_type in ("inference", "chat", "generate", "ask")
            ):
                plan = await self._decompose_task(task_type, payload, context, complexity)
                if plan.strategy != "single" and len(plan.sub_tasks) > 1:
                    result = await self._execute_plan(
                        task_id, plan, context, root_frame, current_depth
                    )
                    sub_tasks_spawned = len(plan.sub_tasks)
                else:
                    result = await self._direct_inference(
                        task_id, task_type, payload, context, root_frame, complexity
                    )
            else:
                result = await self._direct_inference(
                    task_id, task_type, payload, context, root_frame, complexity
                )

        except Exception as exc:
            logger.exception("[rlm:%s] handle_task error: %s", self.name, exc)
            result = AgentResult(
                task_id=task_id, agent_name=self.name,
                success=False, error=str(exc),
            )
        finally:
            duration_ms = (time.time() - start) * 1000
            self.context_manager.pop_frame(
                root_frame.frame_id,
                summary=(result.output or {}).get("response", "")[:200] if result.success else None,
            )

        # Record metrics
        metrics = TaskMetrics(
            task_id=task_id, task_type=task_type, complexity=complexity,
            success=result.success, duration_ms=duration_ms,
            tokens_used=root_frame.tokens_used, model_used=result.model_used,
            delegation_depth=current_depth, sub_tasks_spawned=sub_tasks_spawned,
        )
        self._record_metrics(metrics)

        return result

    # ─── Direct Inference ─────────────────────────────────────────────────────

    async def _direct_inference(
        self,
        task_id: str,
        task_type: str,
        payload: dict,
        context: AgentContext,
        frame: ContextFrame,
        complexity: float,
    ) -> AgentResult:
        """Single-pass LLM inference with memory context injection."""
        prompt = payload.get("prompt") or payload.get("message") or payload.get("query", "")
        if not prompt:
            return AgentResult(
                task_id=task_id, agent_name=self.name,
                success=False, error="No prompt in payload",
            )

        # Inject system prompt
        if not any(t.role == "system" for t in context.history):
            context.add("system", self.config.system_prompt)
            frame.add_message("system", self.config.system_prompt, Priority.CRITICAL)

        # Inject memory context if available
        memory_context = self._build_memory_context(prompt, complexity)
        if memory_context:
            frame.add_message("system", memory_context, Priority.HIGH)
            # Prepend as a system message (not saved to main context)
            memory_injection = {"role": "system", "content": memory_context}
        else:
            memory_injection = None

        context.add("user", prompt)
        context.trim()
        frame.add_message("user", prompt, Priority.HIGH)

        messages = context.to_messages()
        if memory_injection:
            # Insert memory before the last user message
            messages.insert(-1, memory_injection)

        response = await self.chat(messages, task_type=task_type)
        context.add("assistant", response)
        frame.add_message("assistant", response, Priority.MEDIUM)

        # Store useful response patterns in session memory
        self._observe_response(prompt, response, task_type)

        return AgentResult(
            task_id=task_id,
            agent_name=self.name,
            success=True,
            output={"response": response, "session_id": context.session_id},
            model_used=self.config.model,
            metadata={
                "complexity": round(complexity, 3),
                "frame_id": frame.frame_id,
                "tokens_used": frame.tokens_used,
            },
        )

    # ─── Task Decomposition ───────────────────────────────────────────────────

    async def _decompose_task(
        self,
        task_type: str,
        payload: dict,
        context: AgentContext,
        complexity: float,
    ) -> DecompositionPlan:
        """
        Ask the LLM to decompose a complex task into sub-tasks.

        Returns a DecompositionPlan.  Falls back to "single" strategy on any
        error, ensuring we always have a usable result.
        """
        prompt = payload.get("prompt") or payload.get("message") or payload.get("query", "")

        decompose_prompt = (
            f"You must decompose the following task into at most {self.MAX_SUB_TASKS} "
            "focused sub-tasks that can be handled by specialist agents.\n\n"
            f"Task: {prompt[:1000]}\n\n"
            "Respond ONLY with a JSON object matching this schema:\n"
            '{"strategy": "parallel"|"sequential", "rationale": "...", '
            '"sub_tasks": [{"task_type": "chat"|"code"|"search"|"summarize", '
            '"description": "...", "prompt": "..."}]}\n'
            "If the task is simple enough to handle directly, respond with: "
            '{"strategy": "single", "rationale": "Simple enough for direct inference", "sub_tasks": []}'
        )

        try:
            raw = await self.chat(
                [
                    {"role": "system", "content": "You are a task planner for an AI agent mesh. Output valid JSON only."},
                    {"role": "user", "content": decompose_prompt},
                ],
                max_tokens=1024,
                temperature=0.2,
            )
            # Extract JSON from response (may have markdown fences)
            json_match = re.search(r"\{.*\}", raw, re.DOTALL)
            if not json_match:
                raise ValueError("No JSON in decomposition response")
            plan_data = json.loads(json_match.group())

            strategy = plan_data.get("strategy", "single")
            if strategy == "single":
                return DecompositionPlan(strategy="single")

            sub_tasks = []
            for st in plan_data.get("sub_tasks", [])[:self.MAX_SUB_TASKS]:
                sub_tasks.append(SubTask(
                    task_type=st.get("task_type", "chat"),
                    payload={"prompt": st.get("prompt", st.get("description", ""))},
                    description=st.get("description", ""),
                ))

            if not sub_tasks:
                return DecompositionPlan(strategy="single")

            return DecompositionPlan(
                strategy=strategy,
                sub_tasks=sub_tasks,
                rationale=plan_data.get("rationale", ""),
            )

        except Exception as exc:
            logger.debug("[rlm:%s] decomposition failed (%s), using single strategy", self.name, exc)
            return DecompositionPlan(strategy="single")

    async def _execute_plan(
        self,
        task_id: str,
        plan: DecompositionPlan,
        context: AgentContext,
        parent_frame: ContextFrame,
        current_depth: int,
    ) -> AgentResult:
        """
        Execute a DecompositionPlan by delegating sub-tasks.

        Parallel strategy: all sub-tasks run concurrently.
        Sequential strategy: sub-tasks run in order, each gets the output
        of the previous as additional context.
        """
        budget_per_child = 1.0 / len(plan.sub_tasks)

        if plan.strategy == "parallel":
            sub_results = await self.delegate_parallel(
                [(st.task_type, st.payload) for st in plan.sub_tasks],
                context=context,
                depth=current_depth,
            )
        else:
            # Sequential: thread results through
            sub_results = []
            accumulated_context = AgentContext(session_id=context.session_id)
            for turn in context.history:
                accumulated_context.history.append(turn)

            for st in plan.sub_tasks:
                res = await self.delegate(
                    st.task_type, st.payload,
                    context=accumulated_context,
                    depth=current_depth,
                )
                sub_results.append(res)
                if res.success and isinstance(res.output, dict):
                    # Feed result into next sub-task's context
                    accumulated_context.add(
                        "assistant",
                        f"[{st.task_type} result]: {res.output.get('response', '')[:500]}"
                    )

        # Aggregate sub-results into final response
        successful = [r for r in sub_results if r.success]
        if not successful:
            return AgentResult(
                task_id=task_id, agent_name=self.name,
                success=False,
                error=f"All {len(sub_results)} sub-tasks failed",
            )

        parts = []
        for i, (st, res) in enumerate(zip(plan.sub_tasks, sub_results), 1):
            if res.success and isinstance(res.output, dict):
                parts.append(f"**[{i}. {st.description or st.task_type}]**\n{res.output.get('response', '')}")

        aggregated_response = "\n\n".join(parts)

        # Final synthesis pass: ask the agent to synthesize sub-results
        synthesis_prompt = (
            f"Synthesize the following {len(parts)} sub-task results into a coherent, "
            "complete response:\n\n" + aggregated_response[:4000]
        )
        try:
            synthesis = await self.chat(
                [
                    {"role": "system", "content": self.config.system_prompt},
                    {"role": "user", "content": synthesis_prompt},
                ],
                task_type="summarize",
            )
        except Exception:
            synthesis = aggregated_response  # fall back to raw aggregation

        return AgentResult(
            task_id=task_id,
            agent_name=self.name,
            success=True,
            output={
                "response": synthesis,
                "sub_task_count": len(plan.sub_tasks),
                "plan_strategy": plan.strategy,
                "sub_results": [
                    {"task_type": st.task_type, "success": r.success}
                    for st, r in zip(plan.sub_tasks, sub_results)
                ],
            },
            model_used=self.config.model,
            metadata={
                "frame_id": parent_frame.frame_id,
                "decomposed": True,
                "plan_rationale": plan.rationale,
            },
        )

    # ─── Tool System ──────────────────────────────────────────────────────────

    def register_tool(
        self,
        name: str,
        description: str,
        handler: Callable,
        keywords: Optional[list[str]] = None,
    ) -> None:
        """Register an agent-callable tool with NL dispatch support."""
        self._tools[name] = ToolEntry(
            name=name,
            description=description,
            handler=handler,
            keywords=keywords or [],
        )
        logger.debug("[rlm:%s] tool registered: %s", self.name, name)

    async def call_tool(self, name: str, **kwargs) -> Any:
        """Call a registered tool by name."""
        tool = self._tools.get(name)
        if tool is None:
            raise KeyError(f"Unknown tool: {name!r}. Available: {list(self._tools)}")
        return await tool.handler(**kwargs)

    def parse_tool_call(self, instruction: str) -> Optional[tuple[str, dict]]:
        """
        Natural language tool dispatch (VESPER-inspired).

        Maps plain-English instructions to the best-matching registered tool.
        Returns (tool_name, kwargs) or None if no match.

        Examples:
            "search the web for quantum computing news" → ("web_search", {"query": ...})
            "run this code: print('hello')"             → ("python_repl", {"code": ...})
            "remember that the user prefers dark mode"  → ("memory_store", ...)
        """
        instruction_lower = instruction.lower()
        best_tool: Optional[str] = None
        best_score = 0

        for name, tool in self._tools.items():
            score = 0
            # Check keyword matches
            for kw in tool.keywords:
                if kw.lower() in instruction_lower:
                    score += 2
            # Check tool name match
            if name.replace("_", " ") in instruction_lower:
                score += 3
            if score > best_score:
                best_score = score
                best_tool = name

        if best_tool is None or best_score == 0:
            return None

        # Extract a simple argument (everything after the keyword)
        # More sophisticated parsing can be added per-tool
        return best_tool, {"instruction": instruction, "raw": instruction}

    # ─── Python REPL Integration ──────────────────────────────────────────────

    async def run_python(self, code: str, session_id: Optional[str] = None) -> REPLResult:
        """
        Execute Python in a persistent REPL session tied to this agent.

        Args:
            code:       Python code string to execute.
            session_id: REPL session key (default: agent name).

        Returns:
            REPLResult with output, errors, and namespace snapshot.
        """
        sid = session_id or self.name
        result = await REPL_POOL.execute(sid, code)
        logger.debug(
            "[rlm:%s] repl exec (session=%s, success=%s): %s",
            self.name, sid, result.success, code[:80],
        )
        return result

    async def read_webpage(self, url: str) -> str:
        """Fetch a URL and return it as LLM-readable text."""
        result = await self._web_reader.read(url)
        return self._web_reader.format_for_llm(result)

    # ─── Memory Integration ───────────────────────────────────────────────────

    def _build_memory_context(self, prompt: str, complexity: float) -> str:
        """Build a compact memory context block to inject before inference."""
        parts: list[str] = []

        # Session memory (recent patterns for this session)
        session_ctx = self.session_memory.format_for_context(query=prompt, max_entries=5)
        if session_ctx:
            parts.append(session_ctx)

        # Persistent memory (cross-session facts/preferences)
        if self.persistent_memory:
            persistent_ctx = self.persistent_memory.format_for_context(query=prompt, max_entries=5)
            if persistent_ctx:
                parts.append(persistent_ctx)

        return "\n\n".join(parts)

    def _observe_response(self, prompt: str, response: str, task_type: str) -> None:
        """
        Observe a completed inference and extract memorable patterns.

        This is the "subconscious" layer: it passively watches responses and
        stores useful facts without requiring explicit memory calls.
        """
        # Store long, detailed responses as potentially reusable context
        if len(response) > 500 and task_type in ("inference", "generate", "code"):
            snippet = response[:300].replace("\n", " ")
            self.session_memory.store(
                key=f"response_{self._total_tasks}",
                content=snippet,
                category="response_pattern",
                importance=0.3,
                source=self.name,
            )

    # ─── Self-Optimization Loop ───────────────────────────────────────────────

    def _record_metrics(self, metrics: TaskMetrics) -> None:
        """Record task metrics and trigger optimization if threshold reached."""
        self._metrics_log.append(metrics)
        if len(self._metrics_log) > 1000:
            self._metrics_log = self._metrics_log[-1000:]

        self.session_memory.log_interaction(
            task_type=metrics.task_type,
            success=metrics.success,
            duration_ms=metrics.duration_ms,
            model=metrics.model_used,
        )
        self._tasks_since_optimize += 1
        if (
            self.enable_self_optimization
            and self._tasks_since_optimize >= self.OPTIMIZE_EVERY_N
        ):
            # Schedule optimization as a background task (non-blocking)
            asyncio.create_task(self._run_self_optimization())
            self._tasks_since_optimize = 0

    async def _run_self_optimization(self) -> None:
        """
        Self-improvement loop (MiroThinker-inspired MoE optimization).

        Analyses recent task metrics, asks the LLM to suggest strategy
        improvements, and stores them in persistent memory.
        """
        if not self._metrics_log:
            return

        patterns = self.session_memory.extract_patterns()
        recent = self._metrics_log[-self.OPTIMIZE_EVERY_N:]
        avg_duration = sum(m.duration_ms for m in recent) / len(recent)
        success_rate = sum(1 for m in recent if m.success) / len(recent)
        avg_complexity = sum(m.complexity for m in recent) / len(recent)

        perf_summary = (
            f"Recent {len(recent)} tasks: "
            f"success_rate={success_rate:.0%}, "
            f"avg_duration={avg_duration:.0f}ms, "
            f"avg_complexity={avg_complexity:.2f}. "
            f"Patterns: {json.dumps(patterns, indent=None)[:400]}"
        )

        optimization_prompt = (
            "You are analyzing your own recent performance as an AI agent.\n\n"
            f"{perf_summary}\n\n"
            "Identify 1-3 specific, actionable improvements to your task handling strategy. "
            "Focus on: when to decompose vs. handle directly, which task types are slow, "
            "and how to reduce errors. Be concise (3 sentences max)."
        )

        try:
            suggestion = await self.chat(
                [
                    {"role": "system", "content": "You are a self-improving AI agent. Be concise and specific."},
                    {"role": "user", "content": optimization_prompt},
                ],
                max_tokens=256,
                temperature=0.3,
            )
            logger.info("[rlm:%s] self-optimization insight: %s", self.name, suggestion[:200])

            if self.persistent_memory:
                self.persistent_memory.store(
                    key=f"optimization_{int(time.time())}",
                    content=suggestion,
                    category="self_optimization",
                    importance=0.7,
                    tags=["self_improvement", "strategy"],
                    source=self.name,
                )
        except Exception as exc:
            logger.debug("[rlm:%s] self-optimization failed: %s", self.name, exc)

    # ─── Discord Gateway Integration ──────────────────────────────────────────

    async def on_discord_message(
        self,
        message_content: str,
        author_id: str,
        channel_id: str,
        guild_id: Optional[str] = None,
    ) -> str:
        """
        Handle a Discord message and return a response string.

        Creates or reuses a session context per (guild_id, channel_id) pair,
        ensuring conversation continuity within each Discord channel.

        Args:
            message_content: Raw message text from Discord.
            author_id:       Discord user ID.
            channel_id:      Discord channel ID.
            guild_id:        Discord guild (server) ID.

        Returns:
            Response string to send back to Discord.
        """
        session_key = f"discord_{guild_id or 'dm'}_{channel_id}"
        context = AgentContext(session_id=session_key)

        # Store author preference in session memory
        self.session_memory.store(
            key=f"discord_user_{author_id}",
            content=f"Discord user {author_id} in channel {channel_id}",
            category="preference",
            importance=0.4,
            source="discord",
        )

        task_id = str(uuid.uuid4())[:8]
        result = await self.dispatch(
            task_id=task_id,
            task_type="chat",
            payload={"prompt": message_content},
            context=context,
        )

        if result.success and isinstance(result.output, dict):
            response = result.output.get("response", "")
            return self.format_discord_response(response, result)
        return f"⚠️ Error: {result.error or 'Unknown error'}"

    def format_discord_response(self, response: str, result: AgentResult) -> str:
        """
        Format an AgentResult for Discord.

        Truncates to Discord's 2000-char limit and appends a compact metadata
        footer when the task was delegated (decomposed).
        """
        max_len = 1900  # leave room for footer
        truncated = response[:max_len] + "…" if len(response) > max_len else response

        meta = result.metadata
        if meta.get("decomposed"):
            n = result.output.get("sub_task_count", 0) if result.output else 0
            strategy = meta.get("plan_strategy", "?")
            footer = f"\n`[{n} sub-tasks, {strategy}]`"
        else:
            complexity = meta.get("complexity")
            footer = f"\n`[complexity={complexity:.2f}]`" if complexity is not None else ""

        return truncated + footer

    # ─── Default Tools ────────────────────────────────────────────────────────

    def _register_default_tools(self) -> None:
        """Register built-in tools available to all RLM agents."""

        async def _python_repl(code: str, session_id: Optional[str] = None, **_):
            return await self.run_python(code, session_id)

        async def _web_read(url: str, **_):
            return await self.read_webpage(url)

        async def _memory_store(key: str, content: str, category: str = "general", **_):
            if self.persistent_memory:
                return self.persistent_memory.store(key, content, category=category, source=self.name)
            return self.session_memory.store(key, content, category=category, source=self.name)

        async def _memory_retrieve(query: str, **_):
            if self.persistent_memory:
                entries = self.persistent_memory.search(query, top_k=5)
                return "\n".join(f"{e.key}: {e.content[:200]}" for e in entries) or "No results."
            entries = self.session_memory.search(query, top_k=5)
            return "\n".join(f"{e.key}: {e.content[:200]}" for e in entries) or "No results."

        async def _delegate_task(task_type: str, prompt: str, depth: int = 0, **_):
            return await self.delegate(task_type, {"prompt": prompt}, depth=depth)

        self.register_tool("python_repl", "Execute Python code in a persistent REPL.", _python_repl,
                           keywords=["python", "code", "execute", "run", "compute", "calculate"])
        self.register_tool("web_read", "Fetch a URL as text.", _web_read,
                           keywords=["fetch", "read", "url", "webpage", "website", "browse"])
        self.register_tool("memory_store", "Persist a fact or preference.", _memory_store,
                           keywords=["remember", "store", "save", "note", "memorize"])
        self.register_tool("memory_retrieve", "Search memory for relevant facts.", _memory_retrieve,
                           keywords=["recall", "retrieve", "remember", "lookup", "search memory"])
        self.register_tool("delegate", "Delegate a sub-task to a specialist agent.", _delegate_task,
                           keywords=["delegate", "assign", "route", "sub-task", "specialist"])

    # ─── can_handle override ──────────────────────────────────────────────────

    def can_handle(self, task_type: str) -> bool:
        """RLMAgent handles all task types that HermesMoEAgent handles."""
        return super().can_handle(task_type)

    # ─── Status ───────────────────────────────────────────────────────────────

    def status(self) -> dict:
        base = super().status()
        base["rlm"] = {
            "tools": list(self._tools.keys()),
            "context": self.context_manager.status(),
            "session_memory": self.session_memory.status(),
            "persistent_memory": self.persistent_memory.status() if self.persistent_memory else None,
            "metrics_logged": len(self._metrics_log),
            "self_optimization": self.enable_self_optimization,
        }
        return base


# ─── Factory ─────────────────────────────────────────────────────────────────

def create_rlm_agent(
    name: str = "rlm-primary",
    ollama_url: str = "http://localhost:11434",
    ollama_model: str = "llama3.1:8b",
    llamacpp_url: str = "http://localhost:8080",
    lmstudio_url: str = "http://localhost:1234",
    backend: str = "ollama",
    system_prompt: str = (
        "You are MYCONEX, a recursive AI agent in a distributed mesh. "
        "You can decompose complex tasks, delegate sub-tasks to specialist agents, "
        "execute Python code, and search the web. "
        "Be concise, precise, and always aware of your token budget."
    ),
    temperature: float = 0.7,
    max_tokens: int = 4096,
    timeout: float = 120.0,
    max_concurrent: int = 4,
    context_budget: int = 16384,
    max_delegation_depth: int = 4,
    memory_namespace: str = "global",
    enable_self_optimization: bool = True,
    flash_moe_binary: Optional[str] = None,
    experts=None,
) -> RLMAgent:
    """
    Create a production-ready RLMAgent with all components wired.

    Automatically uses HermesMoE expert routing if available, falls back to
    direct Ollama/llamacpp/lmstudio backend otherwise.

    Args:
        name:                    Agent name (also used as REPL session key).
        ollama_url:              Ollama endpoint.
        ollama_model:            Fallback Ollama model.
        llamacpp_url:            llama.cpp server endpoint.
        lmstudio_url:            LM Studio endpoint.
        backend:                 Default backend ("ollama"|"llamacpp"|"lmstudio").
        system_prompt:           Agent system prompt.
        temperature:             Sampling temperature.
        max_tokens:              Max completion tokens.
        timeout:                 HTTP timeout.
        max_concurrent:          Max simultaneous tasks.
        context_budget:          Total token budget for the context tree.
        max_delegation_depth:    Max recursive delegation depth.
        memory_namespace:        Persistent memory namespace key.
        enable_self_optimization: Run self-improvement loop every N tasks.
        flash_moe_binary:        Optional path to flash-moe binary.
        experts:                 Custom MoE expert pool.

    Returns:
        Configured RLMAgent ready to start().
    """
    from pathlib import Path

    config = AgentConfig(
        name=name,
        agent_type="inference",
        model="hermes-moe" if _MOE_AVAILABLE else ollama_model,
        ollama_url=ollama_url,
        llamacpp_url=llamacpp_url,
        lmstudio_url=lmstudio_url,
        backend=backend,
        system_prompt=system_prompt,
        temperature=temperature,
        max_tokens=max_tokens,
        timeout=timeout,
        max_concurrent=max_concurrent,
        role=AgentRole.MANAGER,    # RLMAgent is always a manager
    )

    moe_router = None
    if _MOE_AVAILABLE:
        from integrations.moe_hermes_integration import (
            FlashMoEBackend,
            MoERouter,
            _FLASH_MOE_BINARY,
        )
        binary_path = Path(flash_moe_binary) if flash_moe_binary else _FLASH_MOE_BINARY
        flash_backend = FlashMoEBackend(binary_path=binary_path)
        moe_router = MoERouter(
            experts=experts,
            flash_moe=flash_backend,
            ollama_url=ollama_url,
            ollama_model=ollama_model,
        )

    return RLMAgent(
        config=config,
        moe_router=moe_router,
        context_budget=context_budget,
        max_delegation_depth=max_delegation_depth,
        memory_namespace=memory_namespace,
        enable_self_optimization=enable_self_optimization,
    )
